# Generated by Django 4.2.16 on 2024-10-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitality', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionmedication',
            old_name='medication',
            new_name='medications',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
    ]
