# Generated by Django 4.2.16 on 2024-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_hospitality', '0002_rename_medication_prescriptionmedication_medications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='drug_class',
            new_name='dosage',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='description',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='side_effects',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
